### ISSUE TITLE
Support for sockets

### ISSUE THREAD

**Issue by NielsKoole** [glock45/swifter#100]
Is it possible to add support for sockets? I'm building an app that needs to communicate with another devices in a network without having internet.

Thought of using Swifter as a local http server, which should work. But I prefer a socket connection because of the push capability.

Is this something or are there another ideas for this?

**Comment by glock45** [comment]
hi @NielsKoole do you mean web-sockets ( http://www.html5rocks.com/en/tutorials/websockets/basics/ ) or raw sockets ( https://en.wikipedia.org/wiki/Berkeley_sockets ) ?

**Comment by NielsKoole** [comment]
I think web-sockets will do the job.

**Comment by glock45** [comment]
Swifter has basic support for Web-Sockets. There is a couple of missing features:
+ no Web-Socket client API. 
+ no support for "continuation frames" ( https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#Message_Fragmentation )
This will be added soon :)

**Comment by Bersaelor** [comment]
Hey @glock45 ,

thank you for creating `swifter`. Are you still working on this issue?

I had some measure of success modifying the codebase to allow me to connect to websockets ( https://github.com/Bersaelor/swifter/commit/04d664e431fc2aa4175b9ab8d311422c836b9b59 ).
But there are some issues left, among other things it seems that any message received by the device is immediately sent back as a copy to the browser.
