### ISSUE TITLE
overflows when stored into 'Int'

### ISSUE THREAD

**Issue by bigcoder** [glock45/swifter#101]
When run on ipad ios 9.2 I got these errors:

swifter-master/Sources/String+SHA1.swift:31:25: Integer literal '3285377520' overflows when stored into 'Int'

/swifter-master/Sources/String+SHA1.swift:29:25: Integer literal '2562383102' overflows when stored into 'Int'

/swifter-master/Sources/String+SHA1.swift:28:25: Integer literal '4023233417' overflows when stored into 'Int'

**Comment by glock45** [comment]
@bigcoder thanks for the report :) it looks like you helped me a lot with solving the problem.

The issue is solved by https://github.com/glock45/swifter/commit/b070d440adf0e8d81a927ffa221c047b526350d4
