### ISSUE TITLE
Update Range init in HttpRequest.nextMultiPartBody to conform to Swift 3

### ISSUE THREAD

**Issue by SwimByteRun** [glock45/swifter#102]
While updating my Carthage packages, I received the following warning:

_./Carthage/Checkouts/swifter/Sources/HttpRequest.swift:143:43: warning: 'init(start: end:)' is deprecated: it will be removed in Swift 3.  Use the '..<' operator._

In order to resolve the warning, we need to change the new Range declaration from:
```swift
body.removeRange(Range<Int>(start: body.count-matchOffset, end: body.count))
```
to:
```swift
body.removeRange(Range<Int>(body.count-matchOffset ..< body.count))
```

**Comment by glock45** [comment]
thanks for the report. I am going to replace this section with fopen/fseek API.

best
DK
