### ISSUE TITLE
How to serve a directory?

### ISSUE THREAD

**Issue by whisper-bye** [glock45/swifter#104]
Hi!

I want to load js from html,
here is my code:
```
server["/(.+)"] = HttpHandlers.directory("\(NSBundle.mainBundle().resourcePath!)/build/")
```

html:
```
<body>
    <script type="text/javascript" src="index.bundle.js" charset="utf-8"></script>
</body>
```

but the js file doesn't load

what should I do? thx!

**Comment by glock45** [comment]
For iOS: 
`server["/public/:path"] = HttpHandlers.shareFilesFromDirectory(NSBundle.mainBundle().resourcePath!)`
WebPage:
<body>
    <script type="text/javascript" src="public/index.bundle.js" charset="utf-8"></script>
</body>

**Comment by whisper-bye** [comment]
ok thx
