### ISSUE TITLE
Support custom response headers

### ISSUE THREAD

**Issue by flashspys** [glock45/swifter#19]
I want to set custom http response headers. I saw that headers are set in HttpResponse but there is no option to add custom ones, right?

I tried to work with extensions or inherit HttpResponse but it's an enum and limitied with inheration or extension. If HttpResponse would be a swift class it would be more extensionable for developers.

**Comment by tristaaan** [comment]
I think this can be closed, this line enables custom headers for a response right? 
https://github.com/glock45/swifter/blob/a4f037c8ddad4f249433516529fc11ce9a16e108/Common/DemoServer.swift#L17

**Comment by glock45** [comment]
Added with https://github.com/glock45/swifter/issues/41.

best
