### ISSUE TITLE
Not actually an issue just a question. How to obtain the request ip address?

### ISSUE THREAD

**Issue by jigzat** [glock45/swifter#21]
Thank you for making Swifter available for everyone. I apologize I don't mean to use you as a support agent, but I was wondering, is there any way to obtain the request ip address? 

I wanted to ask one more thing, in my case I need a small web server to send and receive plain text and not to share files or webpages. Is swifter ideal for this scenario? I'm sorry I'm not very versed in this matter.

**Comment by jigzat** [comment]
Ok I made it, I added a remoteAddress parameter to HttpRequest struct, I'm not sure if thats something you want in your code. 

On a side note, can this be threaded?

**Comment by glock45** [comment]
@jigzat hey man, 

the updates are always welcome ! please make a pull request or paste the code here :)

Best

**Comment by jigzat** [comment]
Done, I'm not sure how good it was.

**Comment by glock45** [comment]
hi man, any chance to push the change ?

**Comment by jigzat** [comment]
Hi, I thought I had push it already. Let me check, I'm a github noob.

Enviado desde mi iPhone

**Comment by glock45** [comment]
I moved your code to Socket class and merged it to the mater branch. Once again, thanks for the pull request :)

https://github.com/glock45/swifter/commit/a18e5ee33fadd115f574bb32977a34a9411ae52d

Best

**Comment by jigzat** [comment]
Sorry for the delay I have been very busy this week.

**Comment by glock45** [comment]
no problem :)

**Comment by trozware** [comment]
I have some trouble with this. The "address" reported looks like an IPv6 address e.g. ::101a:400:8060:0
And it changes every few minutes despite no change to my connection.

But when I use `ifconfig` to check my network settings, that address does not appear.
I am running the server and calling it from my dev computer - does this change anything?

Is there a way to tweak this so as to get the IPv4 address?
Even better, can I get the Bonjour name of the caller?

**Comment by vgmoose** [comment]
> Is there a way to tweak this so as to get the IPv4 address?

Really late, but I hit the same issue. Starting the server forceIPv4 gets around it:
```swift
server.start(8080, forceIPv4: true)
```
