### ISSUE TITLE
Swift 2 version?

### ISSUE THREAD

**Issue by JetForMe** [glock45/swifter#28]
Hi Damian. I've got a project that needs an embedded HTTP server, and I thought I'd write it in Swift 2. I found swifter, but unfortunately Xcode 7b1 is unable to convert it completely automatically. Some additional re-write is necessary, and I'm not familiar enough with your code to be sure I'm doing it right.

Any chance you'll branch and update your code to Swift 2? Thanks!

**Comment by xocialize** [comment]
+1 I would really like to see this as well.  Thanks for the great server.

**Comment by glock45** [comment]
Thanks guys. It's ready: https://github.com/glock45/swifter/commit/a4f037c8ddad4f249433516529fc11ce9a16e108

**Comment by JetForMe** [comment]
That was fast! Thanks!
