### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by matteocrippa** [glock45/swifter#3]
Hi, it would be cool if you can add cocoapods ( http://cocoapods.org ) support to your project!

**Comment by czechboy0** [comment]
It is supported in beta. http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/

**Comment by flashspys** [comment]
Now it's fully supported with current version. You can create a podfile :)

**Comment by glock45** [comment]
Added by @ziper1 ( https://github.com/glock45/swifter/pull/31 ).
