### ISSUE TITLE
Close and reopen sockets on suspend-resume?

### ISSUE THREAD

**Issue by JetForMe** [glock45/swifter#30]
Hi. I'm not 100% sure this is what's happening, but it seems that the server sockets are getting closed after the app is suspended a while, and not re-opened. Is it possible for swifter to handle that?

I guess I could handle it, too, killing the server on suspend and re-creating it on resume. Anyway, FYI.

**Comment by glock45** [comment]
Hi. Is this about iOS app ?

**Comment by JetForMe** [comment]
Yes

**Comment by glock45** [comment]
hi man --

iOS closes the sockets when app is in background. If you use one of the background modes, the sockets will be opened (https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html). 

best

best

**Comment by JetForMe** [comment]
I have to close and reopen the sockets when I enter/exit background. It's fine, but an argument could be made that Swifter should do this, since almost always that's what one wants (for the app to continue working when you bring it back to the foreground.

I don't need it to work while it's suspended, just while it's front most. In any case, it's working fine for me when I do that.
