### ISSUE TITLE
What's the tag that indicates that Swifter supports Swift 3.0?

### ISSUE THREAD

**Issue by agisilaos** [glock45/swifter#322]
Hello, 👋 I have multiple dependencies most of them in Swift 3.0, so until the creators of the dependencies decide to support Swift 4.0 I can't use any dependency written in Swift 4.0. What's the tag that indicates that Swifter supports Swift 3.0? Couldn't figure that out myself so I need some help here. Thanks in advance.

**Comment by Vkt0r** [comment]
I think #347 is what you're looking for, we should add the Swift 3 support tag to the `README` though. Would you like to create a PR for it?
