### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by jurex** [glock45/swifter#331]
Hey guys, want to use this library in my iOS app. There are some useful PRs sitting there for a while, so I’m just wondering if this project is still maintained. Thnx

**Comment by JUSTINMKAUFMAN** [comment]
Bump

**Comment by jjorgemoura** [comment]
Cocoapods is still referencing the version 1.4.1 (May) as the last one, not the 1.4.3.

Is it possible to release to Cocoapods?

**Comment by JamesSawley** [comment]
I'm guessing due to the lack of response the answer is no...

**Comment by Vkt0r** [comment]
@JamesSawley @jjorgemoura @jurex The answer is yes 😀. Please refer to the recent merge of #340, #337 and #334. Also, the pod version was updated to 1.4.5.
