### ISSUE TITLE
Overlapping accesses to 'addr' (Xcode 10 beta, Swift 4.2)

### ISSUE THREAD

**Issue by WDDong** [glock45/swifter#336]
In Xcode 10 beta with Swift 4.2 there are two build errors, in Socket.swift (line 51 and 66):
       Overlapping accesses to 'addr', but modification requires exclusive access; consider copying to a local variable

<img width="2096" alt="64c63654-8f23-44b1-8fdc-83361187767f" src="https://user-images.githubusercontent.com/8448083/45480179-f8088080-b77a-11e8-966d-5929ff9fd995.png">

**Comment by WDDong** [comment]
<img width="2096" alt="64c63654-8f23-44b1-8fdc-83361187767f" src="https://user-images.githubusercontent.com/8448083/45480115-cc859600-b77a-11e8-97b7-d2d23cc8419c.png">

**Comment by floriangbh** [comment]
Same issue with Xcode 10 GM version

**Comment by traktor74** [comment]
Same issue =(

**Comment by abrindam** [comment]
Looks like this is already fixed by #318. #332 covers releasing a new version 1.4.3 with this change. Head over to that issue and give it a thumbs up!

**Comment by floriangbh** [comment]
If you are using cartage : `github "glock45/swifter" "b366f5ed088d9d0d216a9ce18ec726f7912c30f3"`

**Comment by ignatovSA** [comment]
You can close the issue, as 1.4.3 is released.
