### ISSUE TITLE
Build Errors, Xcode 10

### ISSUE THREAD

**Issue by kimaldis** [glock45/swifter#339]
Trying to build an oldish app after upgrading to Mojave & Xcode 10 and I'm getting build errors:

<img width="376" alt="screenshot 2018-09-26 at 10 37 25" src="https://user-images.githubusercontent.com/4265299/46071731-94b61f80-c178-11e8-956d-07e24867502a.png">

**Comment by damian-kolakowski** [comment]
1.4.5 should work fine.
