### ISSUE TITLE
Unkown on CocoaPods

### ISSUE THREAD

**Issue by qpre** [glock45/swifter#34]
Hey,
I noticed a [podspec](https://github.com/glock45/swifter/blob/master/Swifter.podspec) file in the repo.
Is there any plan on publishing swifter as a pod ?

**Comment by ziper1** [comment]
Hey,
It's not added to the podspecs master repo https://github.com/CocoaPods/Specs

You need to add git repository address to use it:
```
pod 'Swifter', :git => 'https://github.com/glock45/swifter.git'
```

**Comment by qpre** [comment]
Thanks !

**Comment by essingh** [comment]
Pods seems to think swifter doesn't support osx. Executing "pod install" gives this output:

```
Analyzing dependencies
Pre-downloading: `Swifter` from `https://github.com/glock45/swifter.git`
[!] The platform of the target `talldudekit` (OS X 10.9) is not compatible with `Swifter (1.0.1)`, which does not support `osx`.
```

**Comment by glock45** [comment]
hi guys --

I've just pushed Swifter pod to the Spec ( https://github.com/CocoaPods/Specs/commit/133db899974f022984a657c1335187f5408a9f3a ).



best
