### ISSUE TITLE
update cocoapods version to 1.4.3

### ISSUE THREAD

**Issue by isee15** [glock45/swifter#341]
now pod install from cocoapods  version is 1.4.1.
use
pod 'Swifter', :git => 'https://github.com/httpswift/swifter.git'
to get 1.4.3.

**Comment by yj** [comment]
what about updating the specs repo to make this easer? 

This would especially be good for libs that have a dependency on Swifter ...

**Comment by traktor74** [comment]
the same question guys, will version in cocoapods be updated to 1.4.3 ?

**Comment by DominikBucher12** [comment]
I would mark this super high priority, because right now it fucks up every Project using this  as dependency from dependency. (SlackKit is perfect example)

**Comment by damian-kolakowski** [comment]
the spec repo update (1.4.5).
