### ISSUE TITLE
CI for the repository 

### ISSUE THREAD

**Issue by Vkt0r** [glock45/swifter#349]
We have a small test suite in the library but even with that, we can enable some CI to run with each PR and avoid regressions or any test failure. For OSS we have free support for several providers like CircleCI, Travis, etc.

I'm been working with CircleCI for some time and I can create the environment to add it to the project and talk with the CircleCI support to add the project in the free plan for OSS.

Other options are good too, please let me know your thoughts about it 😅.

CC/ @glock45 @adamkaplan and the rest of the community as well 🎉

**Comment by Vkt0r** [comment]
@glock45 @julien-c @adamkaplan I emailed the CircleCI team to add the repository in the free OSS plans for macOS in order to add CI for the project. They need the repository to be registered in CircleCI so an admin of the organization or the repository needs to add there and then I can contact them to enable the plan for us.

I'm going to add a new PR to CircleCI support as soon as we have the project added there. Can someone of you add the project there, please? Thanks and let me know if you have any doubts.

**Comment by julien-c** [comment]
Sure @Vkt0r, I'll do it right now. Thanks for your help!

**Comment by julien-c** [comment]
@Vkt0r Should be good

**Comment by Vkt0r** [comment]
@julien-c Thanks, I'll let him know to the CircleCI team.

**Comment by Vkt0r** [comment]
@julien-c Is enabled now the plan for the organization thanks again. I'll be creating a PR soon with CI support for the repository.

**Comment by Vkt0r** [comment]
@julien-c Can you verify please that the project is added to CircleCI and running? I created a new PR with support for it but CircleCI is not being trigged for some reason.

**Comment by Vkt0r** [comment]
I checked and the organization is in CircleCI but we need to add the project in CircleCI
