### ISSUE TITLE
Where to find reference documentation ?

### ISSUE THREAD

**Issue by MrSkwiggs** [glock45/swifter#350]

**Comment by Vkt0r** [comment]
@TheSkwiggs I think the best we have for now is the `README` and the source code, unfortunately 😅. But please if you think you can add more docs to the repo that would be helpful.

**Comment by MrSkwiggs** [comment]
@Vkt0r Well the thing is I have no idea how to even use this so writing docs for it would be near to impossible for me at the moment...
