### ISSUE TITLE
WKWebView stays blank

### ISSUE THREAD

**Issue by BeetLab** [glock45/swifter#351]
Hi! I'm launching www folder from Cordova. I'm using server in this way:

`server["/:path"] = shareFilesFromDirectory(wwwPath)
  let request = URLRequest(url: URL(string: "http://localhost:8080")!
  webView.load(request)
`
Server loads every file in www folder, everything is fine, no error logs or smth. App trasport security is set to true. But WKWebView stays blank. Otherwise - if i'm running the same www from Cordova pod web engine - everything is fine. Where should i find the issue?

**Comment by Vkt0r** [comment]
@BeetLab I think you're having issues with the cache. Let's do the following:

1. Reset the simulator's content by erasing its data.
2. Run your code to load the file in the `WKWebView`.

If the `WKWebView` loads your content well, run it again. If you see a blank content then you need to avoid the `localCache` adding to your `URLRequest` the following code before load it in the `WKWebview`:

```swift
request.cachePolicy = .reloadIgnoringLocalCacheData
```

Also, can you verify please using `Charles` or any other HTTP interceptor that your request has the correct `Content-Type`? [`shareFilesFromDirectory `](https://github.com/httpswift/swifter/blob/9c25524169b725128d6b5db719875faf771a96b2/Sources/Files.swift#L22) should add the correct `Content-Type` for you automatically if the file is read it correctly and the `fileRelativePath` is not empty.

**Comment by Vkt0r** [comment]
Closing this. Please feel free to open it in case the solution proposed above doesn't solve it.
