### ISSUE TITLE
ProcessAssertion() Unable to acquire assertion for process with PID 0

### ISSUE THREAD

**Issue by LironGiniApps** [glock45/swifter#360]
Hi, I'm trying to run a local HTTP server which its files are placed in a Bundle object stored in the project(website.bundle).
The project is an iOS project.

My code looks like this:

```
// get website directory path
let bundlePath = Bundle.main.path(forResource: "website1", ofType: "bundle")!
let websiteBundle = Bundle(path: bundlePath)!
let resourcePath = websiteBundle.resourcePath!

// run the server
let server = HttpServer()
server["/:path"] = shareFilesFromDirectory(resourcePath)
try server.start(9080, forceIPv4: true)

// load the url
let url = URL(string: "http://localhost:9080/")!
let request = URLRequest(url: url)
webView.load(request)
```

When running the server on Simulator it's fine and has no issues.
But, when running on a real device I get an error:
`[ProcessSuspension]  0x280a85e40 - ProcessAssertion() Unable to acquire assertion for process with PID 0
`
The index.html file is loaded correctly and starts to load its resources (images, fonts etc. via XMLHttpRequest).

But during the process of loading the resources, the webview reloads the website and leave me with blank page.

I'm using Swifter version 1.4.5 ( currently the latest on the 'stable' branch)

Could you please help me fix this?
Thanks in advance :)

**Comment by adamkaplan** [comment]
Based on a quick search, that exception is most definitely from deep within `WKWebView` and seems correlated with JavaScript issues. One forum post found it happens with memory leaks (i.e. out of memory condition) in JS.

Definitely seems like Swifter should not be the first stop on the blame train. Try hosting your files on the internet or your laptop... very likely it happens when Swifter is not used at all.

**Comment by LironGiniApps** [comment]
Hi Adam,

I've tested my website on Chrome and Safari on my iMac and you are right, the memory does jump by around 1.5 GB, but the page is not reloaded and I believe it's because my iMac has way more RAM than my iPhone does, so WebKit process does not crash.

I guess Swifter can get off the blame train :)
Thank you very much for your response.
Cheers.
