### ISSUE TITLE
Inconsistent semantic version tag discovered in Carthage

### ISSUE THREAD

**Issue by Vkt0r** [glock45/swifter#365]
Recently I ran `carthage outdated` in one of my projects and I was very surprised with the output of Carthage:

```bash
The following dependencies are outdated:
swifter "1.4.5" -> "1.4.5" (Latest: "3.0.0")
```

Our latest release is `1.4.5` but for some reason, we have a discrepancy with the semantic version of the releases, we have `3.0.0`. One easy solution would remove the tag release as it was released in 2016. Change the version of the tag it wouldn't work as Github would be treated as a new release from our branch `stable`. Thoughts?

**Comment by adamkaplan** [comment]
Delete them if nobody should be using them. There are also tags for 2.0.0, 2.0.1 and 2.0.2 as well...

**Comment by Vkt0r** [comment]
Agree, let's fix it.
