### ISSUE TITLE
Xcode 10.2beta compilation issue

### ISSUE THREAD

**Issue by platonsi** [glock45/swifter#369]
Hello,

There seems to be an issue when compiling Swifter on Xcode 10.2beta. The Errno.swift file produces a compilation error on [line](https://github.com/httpswift/swifter/blob/stable/Sources/Errno.swift#L13):

`return String(cString: UnsafePointer(strerror(errno)))`

The recommendation to fix this issue is to remove the call to the UnsafePointer. 

`return String(cString: strerror(errno))`

You can also follow the discusson on [apple forums](https://forums.developer.apple.com/thread/113919)

Cheers
Plato

**Comment by Vkt0r** [comment]
Thank you for reporting this @platonsi. There is a PR with a discussion about it you can see in #367.
