### ISSUE TITLE
can we use this with Objective C?

### ISSUE THREAD

**Issue by theRealGupta** [glock45/swifter#372]
@glock45   my project is completely in objective C. So In project [CocoaHTTPServer ](https://github.com/robbiehanson/CocoaHTTPServer) was used but that is not working properly. so can I use this with Objective C?

**Comment by Vkt0r** [comment]
I don't think you can use it in ObjC as we're not exporting anything to be used in ObjC (`@objc`) so the interoperability it shouldn't work.
