### ISSUE TITLE
server.start() doesn't actually do anything

### ISSUE THREAD

**Issue by jalavosus** [glock45/swifter#376]
When trying to run the following code (more or less copied from the readme)

```
import Swifter
import Foundation

func createServer() -> HttpServer {
  let server = HttpServer()

  server["/hello"] = { request in .ok(.text("Hey")) }

  return server
}


let myServer = createServer()
try myServer.start()
```

The HTTP server doesn't actually start. Like, I can run `swift build` just fine, but actually executing the compiled binary just starts and exits normally. I would assume this isn't supposed to happen, but I can't find anything in the documentation about how one should actually start the server (the documentation also fails to mention that you need to have `try` before `server.start()`).

**Comment by Guru-Work** [comment]
yes, I am facing this issue current with the latest `1.4.6` version. 
But when I make the Podfile to use the `1.4.5` specific version, I am able to see that the server starts up and works as expected. 
```
target 'DemoMockUITests' do
    # Pods for testing
    pod 'Swifter', '1.4.5'
end

```

Not sure what changed between `1.4.5` and `1.4.6` but I am guessing should be relatively easily to fix.

**Comment by Vkt0r** [comment]
Hey @Guru-Work @jalavosus, thanks for reporting this. I tried the latest release myself in a new iOS project and everything is working fine. Can you please give me more context about the issue? Where are you testing the latest version?

I can see in the above example that a strong reference to the server is not retained. Is this being tested in a `Playground`? 

Also, I want to point you guys to the iOS and macOS example apps we have in the repository with a bunch of examples about how to use it. You can find it below https://github.com/httpswift/swifter/blob/bdfd5f5d9ef1137ee034287e06f14e1b8794beb3/XCode/SwifterSampleiOS/ViewController.swift#L10

https://github.com/httpswift/swifter/blob/bdfd5f5d9ef1137ee034287e06f14e1b8794beb3/XCode/SwifterSampleOSX/main.swift#L10

I understand your frustration with the docs about the project but that's something we want to fix soon. A new issue has been created to handle it #346.

**Comment by Guru-Work** [comment]
Thanks for the documentation @Vkt0r but unfortunately I still see this issue. I am trying to start the server from the UI Tests module but I guess the context is not important.

I use Xcode 10.1 and Swift 4.2 which is the same as my dev environment for my bigger project as well. 

```
    let server = HttpServer()
    static let shared = HTTPMockServiceLayer()

    private init() {
        do {
            try server.start(8090, forceIPv4: true)
            server["/hello"] = { request in .ok(.text("Hey")) }
            print("Server has started ( port = \(try server.port()) ). Try to connect now...")
        } catch {
            print("Server start error: \(error)")
        }
    }

```    

With the above code when I use `Swifter, 1.4.5` everything works fine but unfortunately not with `Swifter 1.4.6`

**Comment by jalavosus** [comment]
@Vkt0r,

The only context I can give is that I'm trying to build a command line -- non-iOS, non-macOS -- http server. So the iOS examples don't actually help me any, because I'm not starting the server in an app's init function. I'm trying to make it the main process of a command line binary.

**Comment by Vkt0r** [comment]
@Guru-Work @jalavosus Thanks again for taking the time to explain more about the issue. @Guru-Work you made me think when you mentioning the word `UI-Test` and I decided to test the latest version in a big suite and _voila_, I was able to find the bug. 

You're completely right the bug was introduced in the latest version regarding some refactoring I made myself in the `HttpRouter` and unfortunately I didn't create more smart tests to verify any regression, sorry for that 🙁.

I'll create a PR tomorrow after I test the new changes with my `UI_Tests` suite during the rest of the night.

**Comment by Guru-Work** [comment]
Thank you for looking into this @Vkt0r . Do you know if Swifter could also be used as a proxy server and if so, could you please point me towards some sample code?

**Comment by Vkt0r** [comment]
@Guru-Work @jalavosus Can you please point your `Podfile` or `Cartfile` to #382 and give a try with your current repository and let me know if the issue was fixed?

**Comment by Guru-Work** [comment]
Works fine on the forked branch you created PR with. I checked by deleting the pod and then adding the below code on my UI test target 
```
target 'DemoMockUITests' do
    # Pods for testing
    pod 'Swifter', :git => 'https://github.com/Vkt0r/swifter.git',  :branch => 'dynamic-overlapping-trail'
end

```

Thanks works as expected.

Just wondering If there a place to ask questions about Swifter in general. 
I have a question regarding the https implementation for Swifter and I think it would be a very good use case. I also see that the SSL implementation was underway but left without completion.

**Comment by Vkt0r** [comment]
@Guru-Work Thanks for reporting your feedback. Regarding your question:

>Just wondering If there a place to ask questions about Swifter in general.

You can always open an issue and tag it as a question in the repository and you'll receive an answer for someone with knowledge about it.

About your other question:
>Do you know if Swifter could also be used as a proxy server and if so, could you please point me towards some sample code

I never tried actually so I cannot give you an exact answer but I encourage to open an issue and we can investigate if someone is using it in this way or there is a good reference to accomplish it.

**Comment by Vkt0r** [comment]
Closing this. @Guru-Work Please feel free to create more issues regarding your questions above.
