### ISSUE TITLE
HttpRequest Path Includes Query String

### ISSUE THREAD

**Issue by Mazyod** [glock45/swifter#391]
As far as I know, `path` part of a URL is only `/foo` part of `/foo?a=b`. Hence, my surprise when trying to use this library and seeing `path` printing the whole string.

I made a quick fix on my fork to resolve the issue using `URLComponents`, which required me to bump the macOS deployment target `10.9 -> 10.10`.

Please let me know if you're interested in this change, and I'd be happy to contribute this change back to this repo.

https://github.com/Mazyod/swifter/commit/8a474d4212abed2c33f3400e8af31d5c3dc5c288

**Comment by Vkt0r** [comment]
Hey, @Mazyod This is interesting, thanks from bringing this up! Please create a PR with your changes and I would be happy to review it.
