### ISSUE TITLE
Use Foundation Base64Encoding

### ISSUE THREAD

**Issue by Mazyod** [glock45/swifter#394]
Hello again,

Just stumbled across the base64 implementation in this library, and would suggest it to be switched to use the one provided from Foundation. Happy to open a PR with the change if it's something you'd want. I would also suggest removing the extension and its tests in the future.

https://github.com/Mazyod/swifter/commit/d82f50460e00e23b6c081454f0fcf2df13f01858

**Comment by Vkt0r** [comment]
Hey, @Mazyod sorry for the delay. Thanks for your suggestion and it makes a lot of sense to me to use the base64 encoding algorithm from Apple in `Foundation`. I would be happy to review your PR !
