### ISSUE TITLE
Automatic Content-Type?

### ISSUE THREAD

**Issue by JetForMe** [glock45/swifter#40]
It would be cool if using the `.JSON`, et al. response mechanism, it automatically set the response Content-Type header appropriately.

Thanks!

**Comment by glock45** [comment]
@JetForMe 

hi man, 

i've added it: https://github.com/glock45/swifter/commit/2f45bc8fff8793d9eee6bcce63cab7edbf4490b7#diff-408ba59492b185727c1f82cf517a3c28R98

best
