### ISSUE TITLE
Setting response headers?

### ISSUE THREAD

**Issue by JetForMe** [glock45/swifter#41]
How does one set the response headers?

**Comment by tristaaan** [comment]
Related to #19, looks like it's not supported yet?

**Comment by JetForMe** [comment]
I've submitted a pull request that fixes it for for the known types (e.g. .JSON).

**Comment by tristaaan** [comment]
I've been thinking how this could be expanded, I feel like all the enums are limiting. I'd like to use Swifter to pass some gzipped headers with only png files, if a user could pass custom rules to determine headers that'd be cool. 

Something that receives an array of closures `[ (input) -> String ]` which evaluates `input` and if true returns a header to append for each. I'll look into it but I'd like to see some PR's that would help this issue merged first.

**Comment by glock45** [comment]
hi guys --

I modified the RAW type. It's possible to respond with custom headers. 

best
