### ISSUE TITLE
Support different response based on different request body?

### ISSUE THREAD

**Issue by witchlock** [glock45/swifter#411]
When work with `graphql` the url is always the same and query is based on request body which is not easy to be matched in `swifter`, any solution or suggestion? thanks.

**Comment by witchlock** [comment]
managed to convert `[UInt]` body to `string` to search. Not ideal but work.

**Comment by Guru-Work** [comment]
@witchlock  : can you elaborate on how you solved this or copy paste the snippet of code which helped you. I agree that this is not the best way to solve it and will be useful if swifter can differentiate between request parameters or request headers.
