### ISSUE TITLE
Version 1.4.6 doesn't support swift 5.0

### ISSUE THREAD

**Issue by prasann-1433** [glock45/swifter#414]
**Description:**
While using the swift 1.4.6 looks like having issue with swift 5 and hence not able to run it properly using xCode 10.2 which uses swift 5.0. 

When we point to "stable branch" it seems to be working fine with swift 5.0, but since this is not an officially declared branch, we are looking for an officially release branch which can be consumed. 

Please treat this is as critical bug and quick address of the issue will be much appreciated.

**Comment by Vkt0r** [comment]
@prasann-1433  Thanks for your report. I'll be releasing a new version this weekend.

**Comment by Vkt0r** [comment]
[1.4.7](https://github.com/httpswift/swifter/releases/tag/1.4.7) has been released.
