### ISSUE TITLE
Why Socket is it all Static ?

### ISSUE THREAD

**Issue by zarghol** [glock45/swifter#45]
Socket is a Struct never really used, just by its static method.
We see the socket : CInt as parameter nearly each time,
 but why not use a class, with tcpForListen as init, socketIdentifier Cint as property and avoiding socket parameter and use the class paradigm ??

**Comment by zarghol** [comment]
I can do all modifications, but I want to know why first, if it is for optimization purpose, or not ^^

**Comment by glock45** [comment]
Yeah. We should have Socket class. I would like to switch to the new error handling based on try/catch blocks.
For:
```
Int r = recv(....)
if ( r == -1 ) { ... } 
```
we should have something like:
```
let data = try socket.read()
```
or for:
```
let serverSocket = Socket.tcpForListen(params, *error)
```
it should be converted to:
```
let serverSocket = try Socket.tcpForListen(params)
```
I will keep the issue open.

**Comment by glock45** [comment]
I've checked your pull request ( https://github.com/glock45/swifter/pull/44/commits ) and noticed you actually did what I proposed :)

**Comment by zarghol** [comment]
well, the socket si now class-powered, if you want it :)

**Comment by glock45** [comment]
Yeah ( https://github.com/glock45/swifter/commit/59a248dd1d55f134c6dfdb4e2fb16624d32b7c0e ).
