### ISSUE TITLE
Remove 'Example' target

### ISSUE THREAD

**Issue by apascual** [glock45/swifter#452]
Hi,

Swift Package Manager has issues when two dependencies contain the same target name (https://forums.swift.org/t/multiple-target-issue-with-spm/16696).

The targets should be named properly to avoid conflicts with other libraries.

**Comment by Vkt0r** [comment]
@apascual Thanks for reporting this! Sounds like good PR if you want to go for it.

**Comment by michaelenger** [comment]
This was solved in #492
