### ISSUE TITLE
Compilation in Xcode 12 beta fails with version 1.4.7 from SPM 

### ISSUE THREAD

**Issue by hectorddmx** [glock45/swifter#454]
Hi, when I try to compile for iOS Simulator a project where I use Swifter 1.4.7 (via SPM) with Xcode 12, I get the following error:  
`/Path/To/Project/SourcePackages/checkouts/swifter/XCode/Sources/Socket+File.swift:26:61: Generic parameter 'Element' could not be inferred  `

![image](https://user-images.githubusercontent.com/303818/85362740-d8bc8c80-b4e4-11ea-82d8-8066b818158f.png)

The version from stable works without issues.

**Comment by adellibovi** [comment]
As a workaround you can replace:
`                    let writeResult = write(target, &buffer + writeCounter, readResult - writeCounter)
`
to
`                    let writeResult = write(target, (&buffer + writeCounter) as UnsafeRawPointer, readResult - writeCounter)
`

**Comment by ctreffs** [comment]
Same problem here - but with the cocoa pods  version 👋

**Comment by hectorddmx** [comment]
@adellibovi Thank you! That works as well.
Right now I ended forking the repo and using that as a local development package pointing to the last commit on the stable branch where this is fixed.

Should I close the issue since it'll be fixed on the next tag/release?

**Comment by Vkt0r** [comment]
@lecksfrawen Thanks for reporting the issue, please leave it open to help us to track the issue with Xcode 12. It will be closed when the fix is made.

**Comment by skymobilebuilds** [comment]
After manually editing like suggested by @adellibovi, using Xcode 12 beta 2 I get:

```
Undefined symbols for architecture i386:
  "type metadata for Swift._StringObject.Variant", referenced from:
      outlined init with take of Swift._StringObject.Variant in HttpParser.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

That's being discussed here: https://developer.apple.com/forums/thread/649918

Lottie iOS has the same issue, now solved with this workaround: https://github.com/airbnb/lottie-ios/pull/1215/files

**Comment by drekka** [comment]
Not sure if this helps but I solved this by forking and raising the deployment target from iOS8 to iOS12. 

Which leads me to ask - Does swifter really need to support code that old on the current version?

**Comment by itsthejb** [comment]
My fixes for this currently: https://github.com/httpswift/swifter/compare/stable...itsthejb:xcode12-fixes

- Seems like `buffer` should have array access syntax
- For the `String` issue, disabled 32bit support. Not sure if upstream would want this as a solution, but are there actually many 32bit devices on the market nowadays?

**Comment by Vkt0r** [comment]
Hey, thank you all for your reports regarding Xcode 12 🙏. Now with Xcode 12 beta 4 released this week, I'll try to start a branch with all your feedback to be ready before its release.

**Comment by donly** [comment]
Xcode 12 beta 5 released, how is going please

**Comment by Vkt0r** [comment]
Doing preliminary testing with Xcode 12 beta 5 all it's working fine without any necessary update, it seems Apple fixed the error found in previous versions. I'll be creating a branch for testing today and I'll let you know.

**Comment by Vkt0r** [comment]
Can you please point your `Podfile`, `Cartfile`, or `Package.swift` to the branch `xcode12-swift5` and let me know if any issue appears? Thanks

**Comment by knellr** [comment]
The above branch worked well for me via CocoaPods

**Comment by Vkt0r** [comment]
FYI to specify branches in your:

### Podfile
```ruby
pod 'swifter', :git => 'https://github.com/httpswift/swifter.git', :branch => 'xcode12-swift5'
```

### Cartfile
```ruby
github "httpswift/swifter" "xcode12-swift5"
```

### SPM
```ruby
.package(url: "https://github.com/httpswift/swifter.git'", .branch("xcode12-swift5"))
```

**Comment by hectorddmx** [comment]
I can confirm that branch `xcode12-swift5` with SPM works great with my iOS/tvOS/macOS project in Xcode 12 Beta 6 and Xcode 11.6
![image](https://user-images.githubusercontent.com/303818/91377191-7766b180-e7e4-11ea-9ca9-128b34f6bd23.png)

**Comment by dzyubin48** [comment]
Works good 
Xcode 12 Beta 6, CocoaPods

**Comment by umverteiler** [comment]
Would you mind creating an actual release / tag for this fix? We're using your project as a dependency for a private pod(spec) and in a podspec we couldn't specify a branch as a source, but we'll have to use a tag.

**Comment by Vkt0r** [comment]
@ChristianSteffens Yes definitely, I'll be creating a beta release in the following days. I was waiting to have confirmation from the community about the build. So stay tuned.

**Comment by umverteiler** [comment]
Any news on a release date? This would greatly simplify our current setup.

**Comment by knellr** [comment]
The `xcode12-swift5` branch is working fine for me with the GM & CocoaPods, should we expect a release imminently?

**Comment by Vkt0r** [comment]
@knellr @ChristianSteffens [1.5.0.rc.1](https://github.com/httpswift/swifter/releases/tag/1.5.0.rc.1) has been released.

**Comment by umverteiler** [comment]
I'm not sure, but this version isn't listed in the specs repo - https://github.com/CocoaPods/Specs/tree/master/Specs/4/2/2/Swifter 
🤨

How do I reference this version / tag then? Using `1.5.0.rc.1` as a reference in the podfile doesn't work.

**Comment by Vkt0r** [comment]
@ChristianSteffens That would be my fault 😞. I need to update the Podspec, I'll do later today. Sorry for the inconvenience.

**Comment by Vkt0r** [comment]
@ChristianSteffens @knellr  The Podspecs has been updated. The tag is now [1.5.0-rc.1](https://github.com/httpswift/swifter/releases/tag/1.5.0-rc.1). You should be able to point to `1.5.0-rc.1` now in your Podfile like this:

```ruby
pod 'Swifter', '1.5.0-rc.1'
```

And be sure to run `pod install --repo-update`.

**Comment by umverteiler** [comment]
Works perfectly - thanks a lot.

**Comment by Monte9** [comment]
@Vkt0r unable to install `v1.5.0-rc.1` using Carthage. Created a separate issue for it here: https://github.com/httpswift/swifter/issues/463

Do you think it's related? Or ideas on what might be causing it?

**Comment by jlcvp** [comment]
Any ETA for 1.5.0-rc1 to be published as a stable release?

**Comment by Vkt0r** [comment]
@jlcvp Sure, we should have 1.5.0 published on Monday!

**Comment by jlcvp** [comment]
@Vkt0r Thanks Vkt0r

**Comment by Vkt0r** [comment]
Thank you for all your support and testing. [1.5.0](https://github.com/httpswift/swifter/releases/tag/1.5.0) has been released officially 🚀.
