### ISSUE TITLE
Thread 1: signal SIGABRT

### ISSUE THREAD

**Issue by xiaoxiaotestnote** [glock45/swifter#456]
Report an error directly on this line：
`let server = HttpServer()`
The error is as follows
`Thread 1: signal SIGABRT`

**Comment by Vkt0r** [comment]
Hey, @xiaoxiaotestnote Thanks for taking the time to report this. `SIGABRT` are signal abort but normally you can see the exception attached to the runtime error. Can you please attached the Xcode message or provide a sample project with the reproduction?

**Comment by Vkt0r** [comment]
Please see the latest release and feel free to open this again with more details in case you are still experiencing it.
