### ISSUE TITLE
xcrun lipo -create - Xcode 12 Failure (Carthage)

### ISSUE THREAD

**Issue by Monte9** [glock45/swifter#463]
We use Carthage to install the Swifter package. On Xcode 12 we are currently unable to run the latest version `1.5.0-rc.1` which is suppose to fix it for Xcode 12.

Here's the error:

<img width="950" alt="Screen Shot 2020-09-18 at 5 18 12 PM" src="https://user-images.githubusercontent.com/7840686/93594163-f198e900-f9d2-11ea-9588-a82de176fd5f.png">

**Comment by Monte9** [comment]
I figured it out! Turns out this is unrelated to Swifter. It's a carthage issue.

For anyone else that might run into this in the future - this was the solution: https://github.com/Carthage/Carthage/issues/3019#issuecomment-664099506

**Comment by Vkt0r** [comment]
@Monte9 Glad, you figured out!
