### ISSUE TITLE
Xcode 12 build error

### ISSUE THREAD

**Issue by Alex-Xcl** [glock45/swifter#467]
![image](https://user-images.githubusercontent.com/50492028/94021602-c6553600-fde6-11ea-9ddd-8536986806d8.png)

**Comment by jlcvp** [comment]
this is fixed on the 1.5.0-rc.1, @Vkt0r will release 1.5.0 on the stable channel soon.

**Comment by jlcvp** [comment]
for further details see #454

**Comment by Vkt0r** [comment]
Please see the latest release 1.5.0 and open a new issue if you've any errors. Closing this.
