### ISSUE TITLE
Xcode 12.01 problem

### ISSUE THREAD

**Issue by LuboZ** [glock45/swifter#469]
Im getting **"Generic parameter 'Element' could not be inferred"** error during build on line 26 in file Socket+File.swift 
It started after update of the xcode to latest version.

![image](https://user-images.githubusercontent.com/33423536/95080054-cbd04b80-0717-11eb-94ca-bbecf044337c.png)

**Comment by xNarCiik** [comment]
I have the same problem

I updated the sendFileImp with the latest version of this file (see this commit https://github.com/httpswift/swifter/commit/4d89ac464d2d3b931cadc4a13696b32b2fd0dd3e)

I can build now, but not sure if there is side effect or not

**Comment by DanielStormApps** [comment]
1.5.0 resolves this issue.
