### ISSUE TITLE
SSL encryption

### ISSUE THREAD

**Issue by UBBproject** [glock45/swifter#47]
Is it supported? Or will be?

**Comment by glock45** [comment]
It will be :)

**Comment by UBBproject** [comment]
Hy Damian!
Could you please give me a hint, how i can implement an SSL certificate into this server. I really need to finish my project ASAP. :(
Thank you, in advance!

**Comment by glock45** [comment]
Hi man,

The tutorial can be found here:

https://developer.apple.com/library/mac/documentation/Security/Reference/secureTransportRef/

Best,
DK

**Comment by UBBproject** [comment]
Hi!
Thank you so much! :)

**Comment by macecchi** [comment]
Hi! Any updates on this?
