### ISSUE TITLE
Use Swifty JSON (or any other serializer)

### ISSUE THREAD

**Issue by zarghol** [glock45/swifter#48]
In many projects, I use SwiftyJSON to read and write JSON, and I thought how to use it conveniently with this framework, and here is how I see the thing : 
in HttpResponseBody, instead of serialize inside the switch self, have a generic Serializer protocol to provide a String? with just a method to serialize. in the switch self, we call the appropriate Serializer, and that way, we can extend the serializers we want and override :)
How does it feels ? if you're ok, I do it tomorrow morning

**Comment by glock45** [comment]
Merged ( https://github.com/glock45/swifter/commit/ddfa12148923fca42133d84bc5783413609dac8e ).
