### ISSUE TITLE
Conflict between two routes

### ISSUE THREAD

**Issue by zarghol** [glock45/swifter#49]
If I add a route after adding "/" route, it always redirect with "/" because it matches first.
I try to handle this, just to warn you :)

**Comment by glock45** [comment]
Yeah. That's why the order matters :)

**Comment by zarghol** [comment]
well, not anymore ! I commit (I added also the serializers way)

**Comment by glock45** [comment]
I merged the pull request with the fix for "/" ( https://github.com/glock45/swifter/commit/ddfa12148923fca42133d84bc5783413609dac8e ). I've chosen different approach. It sorts RegExps alphabetically by the .pattern field.
