### ISSUE TITLE
What is the proper way to return custom headers?

### ISSUE THREAD

**Issue by Ricardo1980** [glock45/swifter#495]
Hello,

Right now I am using
`return HttpResponse.ok(.data(myData, contentType: "application/vnd.apple.mpegurl;charset=UTF-8"))
`
But I need to add more custom headers apart from the content tyoe.
Should I use something like this?
```
let headers = [
            "X-Signature": "SOTT client=\"IA-IOS-v1\",signature=\"PpnogGw0D+GdObwuqEUhQU8yk5Y=\",timestamp=\"1628678968\",version=\"1.0\"",
            "X-RequestId":"c6b908ef-be98-47ca-bed1-8179b1dade04"]
            return HttpResponse.raw(200, "OK", headers) { httpResponseBodyWriter in
                return try httpResponseBodyWriter.write([UInt8](utf8String))
            }
```
Thanks a lot for suggestions.

**Comment by paulz** [comment]
one idea is to use middleware to add a handler to modify handler:

https://github.com/httpswift/swifter/blob/67d7c16ce596e3409ba1443b8626e543c6f7c1b4/Xcode/Sources/DemoServer.swift#L199-L202

**Comment by Ricardo1980** [comment]
Thanks a lot @paulz
