### ISSUE TITLE
How to return html with http://192.168.0.1

### ISSUE THREAD

**Issue by whisper-bye** [glock45/swifter#51]
this is my code
```swift
let server = HttpServer()

server["/(.+)"] = HttpHandlers.directory(NSBundle.mainBundle().resourcePath! + "/www")

server.start(80, error: nil)

self.server = server
```

Q: I want to visit index.html with http://192.168.0.1 not http://192.168.0.1/index.html,
what should I do? thx!!!

**Comment by glock45** [comment]
hi @whisper-bye 
```
server["/(.+)"] = HttpHandlers.directory(NSBundle.mainBundle().resourcePath! + "/www")
```
if you deploy your app on iOS, all the resources from "www' directory will  land at the root of "NSBundle.mainBundle().resourcePath" so at the runtime the files are in different directory. "www" directory is not copied. Could you please check what you have in "NSBundle.mainBundle().resourcePath" ? ( it looks like  http://192.168.0.1/index.html works for you and index.html is located at "www" directory ).
```
Q: I want to visit index.html with http://192.168.0.1 not http://192.168.0.1/index.html,
what should I do? thx!!!
```
This should help ( please update Swifter to the latest version ):
```
// for [http://192.168.0.1, http://192.168.0.1/ ]
server ["/"] = HttpHandlers.file("[PATH]/index.html");
```
best
