### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by gabebear** [glock45/swifter#60]
Now that Linux has Swift and GCD... any chance of porting this? https://swift.org

**Comment by m3talsmith** [comment]
I'm going to attempt this over the weekend.

**Comment by glock45** [comment]
xD

**Comment by gabebear** [comment]
IBM's Swift Linux real thing has a http server/client example(server.swift).  http://swiftlang.ng.bluemix.net/#/repl

**Comment by aciidb0mb3r** [comment]
Foundation for linux is not yet complete so very difficult to port this project to linux
even NSString has so many unimplemented method
https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/NSString.swift

**Comment by glock45** [comment]
hi all,

I spend some time on the support for Linux. I worked on Socket class and it compiles successfully on Linux machine ( Ubuntu 15.10 Swift 2.2  ). I also removed NSData dependency from HttpServer and Socket classes ( both use [UInt8] array ).

I am going to continue the journey with the following roadmap: 
1. Remove NSRegularExpression dependency from HttpServer ( maybe together with routing mechanism redesign ).
2. Remove objc_sync_enter/objc_sync_exit dependency from HttpServer.
3. Remove NSURL dependency from HttpServer.

Guys, if you have any ideas or pull requests  please let me know !

best,
dk

**Comment by julien-c** [comment]
Awesome!

Why do you need to remove the NSURL dependency? What's missing in the
current implementation in Foundation core libs?

How can we help?!

Julien

**Comment by glock45** [comment]
@julien-c thanks :)

The following classes works on Linux:
Socket.swift, HttpRequest.swift, HttpParser.swift

TODO: HttpServer, HttpResponse.

best,
dk

**Comment by johnno1962** [comment]
Hi @glock45 if you’re looking for dispatch_async you can try https://github.com/johnno1962/NSLinux

**Comment by glock45** [comment]
hi @johnno1962 

Correct me If I am wrong ? Every time I call dispatch_async the library creates a new thread and after the run all the resources are released ( which is absolutely fine for me ) ?

best
dk

**Comment by gabebear** [comment]
It does look to spin a thread every time... I'm confused why @johnno1962 code would be better than the dispatch_async provided by Apple/Swift? https://github.com/apple/swift/blob/8d9ef80304d7b36e13619ea50e6e76f3ec9221ba/test/ClangModules/Dispatch_test.swift

**Comment by julien-c** [comment]
I've put in some work on the Linux support of `swifter` (in #72, #73, #74, #75). 

One of the last roadblocks on getting basic support (first of all, getting to something that builds 😄) is the locking that happens in `HttpServer`. My question is: is it really needed? If it is, is there something equivalent that we could use in `Glibc`?

**Comment by C0deH4cker** [comment]
@julien-c How about something like https://gist.github.com/kristopherjohnson/d12877ee9a901867f59?

**Comment by C0deH4cker** [comment]
Really it boils down to just using a NSLock and doing:

```
nslock.lock()
closure()
nslock.unlock()
```

**Comment by julien-c** [comment]
@C0deH4cker  Your link seems to 404

**Comment by glock45** [comment]
@julien-c Thanks for a great work ! I pushed two changes more and finally we compile on Linux ( with NSLinux from @johnno1962 ). I have not run it yet xD

@C0deH4cker thanks for NSLock ! I've update Swifter.

**Comment by C0deH4cker** [comment]
@julien-c Whoops, looks like I accidentally removed the last "9"! Try this one: https://gist.github.com/kristopherjohnson/d12877ee9a901867f599

**Comment by C0deH4cker** [comment]
I'll clone it and test on Ubuntu 14.04 now and let you know!

**Comment by glock45** [comment]
( I build on Linux using "swift build" ).

**Comment by C0deH4cker** [comment]
Built both NSLinux.a and Swifter.a. How are you building the samples?

**Comment by julien-c** [comment]
Yay! Swifter server running on Ubuntu here: http://swift.circular.io:8080/ 🎉🎉

**Comment by julien-c** [comment]
The app's code is here: https://github.com/julien-c/example-package-dealer

Small variation on Apple's playing card dealer example. There's a pretty sweet `/cards` endpoint here: http://swift.circular.io:8080/cards

I had to unplug the JSON serialisation as `NSJSONSerialization` is unimplemented in Foundation so far.

**Comment by julien-c** [comment]
I've just posted this to Hacker News, if you wish to upvote :)

**Comment by C0deH4cker** [comment]
Got a demo running on my server as well! Took a little extra time as I didn't realize Azure firewalls new VMs from everything but SSH by default, not using iptables but external to the VM (and it seems that adding a new firewall rule is broken). Great work!

**Comment by johnno1962** [comment]
congrats @glock45. @gabebear You’re right NSLinux’s dispatch_async is pretty inefficient spinning a thread each call but libdipatch seems not to be available on Linux. It should clean up after each thread exits (calls pthread_detach)

**Comment by gabebear** [comment]
oops, interesting, I'd setup my ObjC Linux server long enough ago I'd forgotten how I'd done it. Went back and I've been using http://nickhutchinson.me/libdispatch/ (forgot I'd even installed it)

**Comment by segabor** [comment]
Hi,

Happy to see it runs on Linux at last. Here's my work that makes the example run also, with build script.

https://github.com/segabor/swifter/commit/918a751e1ef02cb0c13c72e20512a1465218fcc1
Cheers,

Gábor

**Comment by sergeydi** [comment]
> Remove objc_sync_enter/objc_sync_exit dependency from HttpServer.

Whan to use on Linux  instead of  objc_sync_enter/objc_sync_exit?
