### ISSUE TITLE
Noob guide

### ISSUE THREAD

**Issue by drnic** [glock45/swifter#61]
For the benefit of people who have never used Swift yet, and perhaps haven't touched XCode since 2008, could you perhaps add a simple getting started guide to creating a simple web app and running it locally to serve traffic?

And/or perhaps link to some web apps built with Swifter. Github searches for "swifter" include matches for "swift"; so I didn't find any so far.

**Comment by aciidb0mb3r** [comment]
open `Swifter.xcodeproj`
set scheme to `SwiftSampleOSX`
hit play button or command+r
open `http://localhost:9080` in your broswer
you should be seeing the demo server

**Comment by glock45** [comment]
@drnic please check this tutorial: http://www.raywenderlich.com/115253/swift-2-tutorial-a-quick-start

best
dk

**Comment by drnic** [comment]
Thanks!
