### ISSUE TITLE
Dependency "swifter" has no shared framework schemes

### ISSUE THREAD

**Issue by monster1025** [glock45/swifter#62]
I didn't find following issue in this project:

On "carthage update" i got following error:
>Dependency "swifter" has no shared framework schemes

I have created clean macos applicattion(cocoa).
Here is my config:
>$ cat Cartfile
>github "glock45/swifter"

>$ carthage update
>*** Fetching swifter
>*** Checking out swifter at "1.0.2"
>*** xcodebuild output can be found in /var/folders/ss/xffzdh1s75sdvv_y2z4q_4l40000gn/T/carthage-xcodebuild.LZbQeX.log
>*** Skipped building swifter due to the error:
>Dependency "swifter" has no shared framework schemes

>If you believe this to be an error, please file an issue with the maintainers at >https://github.com/glock45/swifter/issues/new

>$ cat /var/folders/ss/xffzdh1s75sdvv_y2z4q_4l40000gn/T/carthage-xcodebuild.LZbQeX.log

^^^^^^^ empty

**Comment by SamDecrock** [comment]
Same problem here

```
carthage update
*** Cloning swifter
*** Checking out swifter at "1.0.2"
*** xcodebuild output can be found in /var/folders/s4/q_cy2mv14r34ccl2lp2rk2780000gn/T/carthage-xcodebuild.tjwQBJ.log
*** Skipped building swifter due to the error:
Dependency "swifter" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/glock45/swifter/issues/new
```

**Comment by ParkinWu** [comment]
Same problem
```
*** Fetching swifter
*** Checking out swifter at "1.0.2"
*** xcodebuild output can be found in /var/folders/tj/p25wcr6j7bsb9bjs61w3bz9w0000gn/T/carthage-xcodebuild.XLTNEr.log
*** Skipped building swifter due to the error:
Dependency "swifter" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/glock45/swifter/issues/new
```

**Comment by glock45** [comment]
@Palleas hey man :) can you help here ?

**Comment by solidfox** [comment]
The schemes aren't checked as shared in the 1.0.2 commit. Fix by checking shared in Main Menu > Product > Scheme > Manage Schemes... in Xcode

**Comment by Palleas** [comment]
Oups, maybe I un-shared it somehow before it got merged? My bad!

**Comment by solidfox** [comment]
No worries! I wonder though, that commit seems to also not have any framework targets so it doesn't work with Carthage anyways. Using `github "glock45/swifter" "master"` works as a temporary fix until there's a new release but I wouldn't recommend it as it uses the current development version of Swifter.

**Comment by glock45** [comment]
I've fixed schemes for the Swift project and it works fine now:
```
~/D/TestCarthage> echo 'github "glock45/swifter" == 1.0.3' > Cartfile
~/D/TestCarthage> carthage update
*** Fetching swifter
*** Checking out swifter at "1.0.3"
*** xcodebuild output can be found in /var/folders/_9/8qnpz5_54x7_5h3r53czb63m0000gn/T/carthage-xcodebuild.88qNxm.log
*** Building scheme "SwifterMac" in Swifter.xcodeproj
*** Building scheme "SwifteriOS" in Swifter.xcodeproj
damiankolakowski@Damian ~/D/TestCarthage> ls -la Carthage/Build/
drwxr-xr-x  4  staff  136 Dec 20 00:51 .
drwxr-xr-x  4  staff  136 Dec 20 00:51 ..
drwxr-xr-x  4  staff  136 Dec 20 01:01 Mac
drwxr-xr-x  6  staff  204 Dec 20 01:01 iOS
```
