### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by mohdabdurraafay** [glock45/swifter#63]
Do we plan to support Linux with latest open sourced tool-chain?

**Comment by glock45** [comment]
hi @mohdabdurraafay :) this topic is already discussed here: https://github.com/glock45/swifter/issues/63

best,
dk

**Comment by mohdabdurraafay** [comment]
#63 is this same thread. I think you intend to point me elsewhere.

**Comment by glock45** [comment]
ooops :) sorry, here you have the correct link https://github.com/glock45/swifter/issues/60
