### ISSUE TITLE
Swift Package Manager tag

### ISSUE THREAD

**Issue by harlanhaskins** [glock45/swifter#65]
Could you tag a new release with the Package.swift file?

**Comment by cwagdev** [comment]
+1 not sure if that's the cause for my issue but I am seeing the following

```
Cloning Packages/swifter
swift-build: The dependency graph could not be satisifed (https://github.com/glock45/swifter.git)
```

With a `Package.swift` of:

```swift
import PackageDescription

let package = Package(
  name: "MySwiftPackage",
  targets: [],
  dependencies: [
    .Package(url: "https://github.com/glock45/swifter.git", majorVersion: 1)
  ]
)
```

**Comment by harlanhaskins** [comment]
It's definitely the cause.

`majorVersion: 1` means that it's going to look for a tag called `1.0.0`, which this project doesn't have.

You'll need to use the `.Package(url: String, _ version: Version)` initializer.

`.Package(url: "https://github.com/glock45/swifter.git", Version(1, 0, 2))`

But that tag doesn't have Package.swift as it was created in October.

**Comment by cwagdev** [comment]
I believe `majorVersion: 1` finds the highest `1.x.x` version. I was just able to get `swift build` to pass by forking and creating a `1.0.3` tag on my fork.

```swift
import PackageDescription

let package = Package(
  name: "MySwiftPackage",
  targets: [],
  dependencies: [
    .Package(url: "https://github.com/cwagdev/swifter.git", majorVersion: 1)
  ]
)
```

**Comment by harlanhaskins** [comment]
Ooh, really? I thought it found the lowest version! That's great. Thanks!

**Comment by NSBrianWard** [comment]
Just curious if this is on the plan for resolution in the near future. Currently I'm on the fork, but I'd love to jump back in the main branch ASAP. Thanks!

**Comment by julien-c** [comment]
Planning on tagging a release later today, once I merge a `main.swift` example file for Linux.

**Comment by glock45** [comment]
@harlanhaskins @cwagdev @NSBrianWard @julien-c 
We got a new release 1.0.5.
