### ISSUE TITLE
HttpServer has no public initializer

### ISSUE THREAD

**Issue by crayment** [glock45/swifter#85]
- Xcode 7.2
- Swifter 1.0.5

-

![](http://cl.ly/2R0R0T051Y1t/Image%202015-12-21%20at%204.42.53%20PM.png)

-

Image from sample project:

![](http://cl.ly/1x3a3d1o0g0D/Image%202015-12-21%20at%204.58.43%20PM.png)

**Comment by glock45** [comment]
oops :+1: I forgot about "public override init() { }" for HttpServer class :)

**Comment by glock45** [comment]
one again, thanks for the report. It's fixed by https://github.com/glock45/swifter/commit/3eecb3204170b7583ff2076ff995b556dbdaf4f0

I am going to release the next version.

**Comment by glock45** [comment]
@crayment could you please check the latest release (1.0.6) ?

**Comment by crayment** [comment]
Confirmed working on 1.0.6 :+1: Thanks!!
