### ISSUE TITLE
How to get server port and ip address?

### ISSUE THREAD

**Issue by aurasw** [glock45/swifter#86]

**Comment by weaksauce** [comment]
ip address is whatever address your machine has and port is configurable but 8080 by default 

https://github.com/glock45/swifter/blob/master/Sources/HttpServerIO.swift#L20

**Comment by glock45** [comment]
for MacOS: http://127.0.0.1:9080
for iOS Simulator: http://127.0.0.1:8080
for iOS Device: http://[iphone_ip_address]:8080

**Comment by omerlh** [comment]
Hey, 
I've run into the same problem. I've planned to use the server for testing http related code (e.g. run the server, mock the response, and send the code to request data from the mock server).
That's what I've tried so far:
```swift
        let server = HttpServer()
        server["/hello"] = { (req: HttpRequest) in return HttpResponse.OK(HttpResponseBody.Html("You requested " + req.address!)) }
        try! server.start()
        let expectaion = expectationWithDescription("something")
        
        let session = NSURLSession(configuration: NSURLSessionConfiguration.defaultSessionConfiguration())
        let task = session.dataTaskWithURL(NSURL(fileURLWithPath: "http://127.0.0.1:8080/hello"), completionHandler: {(data, res, err) in
            print(data)
            expectaion.fulfill()
            })
        
        task.resume()

        waitForExpectationsWithTimeout(30) { (err) -> Void in
            if let error = err {
                print("hey")
            }
        }
```
But the request failed with nsdomain error. I've also put breakpoint in httpserverio after ```self.listenSocket.acceptClientSocket()``` but not incoming request received. I've tried also using localhost or the device ip as the address, but no luck so far.
Could you help?

Thanks.
Omer
