### ISSUE TITLE
What is the correct way to link an external style sheet file

### ISSUE THREAD

**Issue by roman-yu** [glock45/swifter#88]
Hi,
I created a /Resources/Web directory as "Folder references" under my project root directory. The structure is shown below:
```
-Web:
  -css:
    bootstrap.min.css
  -js:
    index.html
```
The html can be retrieved with ```html = NSData(contentsOfFile:"\(rootDir)/Web/index.html")``` and shown in the browser, but linking to external css failed in the Chrome console.

Below is the link tag in my ```index.html```. I am wondering why it not works.
```
<head>
<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
...
</head>
```

If above is not an option, does that mean css files also need to be retrieved like html files and then insert the css text into the head place of the html text, and return?

Thanks very much!
Roman

**Comment by glock45** [comment]
hi @roman-yu 

could you please give me a screenshot from Target -> Build Phases -> Copy Files settings section ?

best
dk

**Comment by papierschiff** [comment]
there is a problem with paths in swifter.
now
```server["/resources/:file"] = HttpHandlers.directory(publicDir)```
matchs resources/file.css but not resources/css/file.css

this could be fixed with something like
```server["/resources/:path"] = HttpHandlers.directory(publicDir)
        server["/resources/:folder/:file"] = HttpHandlers.directory(publicDir)```

but since 8fecb351c5c27a0df5724f596742133c1a5d81bc this would be a little compilicated.

**Comment by roman-yu** [comment]
Below is my project structure, please take a look:
![screen shot 2016-01-14 at 11 48 48 am](https://cloud.githubusercontent.com/assets/5867845/12315367/17158844-bab5-11e5-8348-3b1a1a5751e0.png)

**Comment by tannernelson** [comment]
@roman-yu you should take a look at my fork of this project https://github.com/tannernelson/vapor 

It has a Public folder where you can easily put all of your style sheets / images that you want publicly available.

**Comment by glock45** [comment]
@roman-yu thanks for the feedback. You are right. It does not work. I fixed it here: https://github.com/glock45/swifter/commit/25e9da7acb89f48934e1a7ae8f7d3d476d1ea344

I am going to release a new version - 1.0.9 with other cool stuff.

@tannernelson You did not fork Swifter. You copied source files to your repo and removed license headers.

**Comment by nrmtrifork** [comment]
This is a great idea! However it is not released in 1.0.9, it probably going to be released in 1.0.10. Because 25e9da7 is not tagged with "1.0.9".

**Comment by glock45** [comment]
@nrmtrifork :+1:

**Comment by tannernelson** [comment]
@glock45 There's attribution in the README. I can put the license headers back in the files from this repo. They just seem a little redundant to me.

**Comment by glock45** [comment]
@tannernelson Yes, please do that. I believe in your good intentions but there are more examples of how you break the rules:

I see copy of @johnno1962 's NSLinux ( https://github.com/johnno1962/NSLinux/blob/master/Sources/Dispatch.swift#L48 ) at your repo ( https://github.com/tannernelson/vapor/blob/master/Sources/LinuxFixes.swift#L156 ). No attribution.

I think you are about to start professional carrier and don't really pay attention to the licensing. Please think about all those guys from here who spend long evenings to make it work.

**Comment by tannernelson** [comment]
@glock45 Very good point–you're right. 

https://github.com/tannernelson/vapor/commit/7dc51746ebc0d99cf333164d97ff997e3137d157

As for forking, Vapor's `Response` class is already too different to take advantage of re-basing or merging updates from the forked repo I think. 

But I'm going to continue watching this repo and contributing for sure.

**Comment by glock45** [comment]
@tannernelson :+1: thanks man

**Comment by roman-yu** [comment]
@glock45, that's great, looking forward to the new version!

@tannernelson, thanks I will take a look.
