### ISSUE TITLE
HttpRequest.MultiPart missing member 'name' and 'fileName' (when using Carthage)

### ISSUE THREAD

**Issue by Laban1** [glock45/swifter#89]
I included Swifter 1.0.6 in my project using Carthage and then simply copied the server.POST["/upload"] block from demoServer.swift, but the line:

`response += "Name: \(multipart.name) File name: \(multipart.fileName) Size: \(multipart.body.count)<br>"` does not build.  I get unresolved identifier, *"value of type 'HttpRequests.MultiPart' has no member 'fileName' "* (and the same for .name).

Note that if I download the full source from GitHub, everything builds and runs just fine - the issue is only when I use Carthage to include Swifter in my project.  Lastly, I am new to both Xcode & swift, so if I am missing something stupid, please let me know what...

**Comment by glock45** [comment]
hi @Laban1 

Thanks for the report. Multipart was not in 1.0.6 release. I've added is just now ( 1.0.7 ).

best
dk

**Comment by Laban1** [comment]
Thanks, works fine now!!  Minor note: the Readme.md file still has 1.0.6 for Carthage.

**Comment by glock45** [comment]
@Laban1 thanks !
