### ISSUE TITLE
type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by MXPicture** [glock45/swifter#91]
Hi

I get the error "type of expression is ambiguous without more context" when I use .Html() this way:
server["/hello"] = { .OK(.Html("You asked for ")) }

why does the following work and mine not?
server["/hello"] = { .OK(.Html("You asked for " + $0.path)) }
Thanks

**Comment by glock45** [comment]
hi :)

it's because of swift's syntax :( According to (https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Closures.html) it's not possible and you need to provide argument list before ".OK(...".

> If you use these shorthand argument names within your closure expression, you can omit the closure’s argument list from its definition, and the number and type of the shorthand argument names will be inferred from the expected function type.

It should work if you change it to:
```
server["/magic"] = { _ in .OK(.Html("You asked for ")) }
```

best,
dk
