### ISSUE TITLE
Release 1.0.7 is not on Cocoapods

### ISSUE THREAD

**Issue by nrmtrifork** [glock45/swifter#92]
According to cocoapods.org Swifter is still 1.0.6! Can this be updated?

**Comment by nrmtrifork** [comment]
More than that it seems that depending on 1.0.6 does not refer to right commits. Are there anything wrong with the tags or the podspec?

**Comment by nrmtrifork** [comment]
Please run "pod trunk push Swifter.podspec", who ever is entitled to do so

**Comment by glock45** [comment]
hi @nrmtrifork 

can you try please with 1.0.9 ?

best
dk

**Comment by nrmtrifork** [comment]
Perfect! It works. Thanks
