### ISSUE TITLE
How to save data with upload?

### ISSUE THREAD

**Issue by swierpa** [glock45/swifter#95]
Hi, I'm trying to use the upload function as shown in sample project. Anyway I'm not able to save the file uploaded in a folder in device.. I also can't find anything about this in source code.. Can you please help me? My actual code is:
    
       let server = HttpServer()
        
       let publicDir = NSBundle.mainBundle().resourcePath
        
        
       server["/resources/:file"] = HttpHandlers.directory(publicDir!)
        
       server.GET["/login"] = { r in
            if let rootDir = publicDir, html = NSData(contentsOfFile:"\(rootDir)/login.html") {
                var array = [UInt8](count: html.length, repeatedValue: 0)
                html.getBytes(&array, length: html.length)
                return HttpResponse.RAW(200, "OK", nil, { $0.write(array) })
            }
            return .NotFound
        }
        
        server["/hello"] = { r in
            if let rootDir = publicDir, html = NSData(contentsOfFile:"\(rootDir)/upload.html") {
                var array = [UInt8](count: html.length, repeatedValue: 0)
                html.getBytes(&array, length: html.length)
                return HttpResponse.RAW(200, "OK", nil, { $0.write(array) })
            }
            return .NotFound
        }
        
        server.POST["/upload"] = { r in
            var response = ""
            for multipart in r.parseMultiPartFormData() {
                response += "Name: \(multipart.name) File name: \(multipart.fileName) Size: \(multipart.body.count)<br>"
            }
            return HttpResponse.OK(.Html(response))
        }
                
        server.POST["/login"] = { r in
            let formFields = r.parseUrlencodedForm()
            return .MovedPermanently("/hello")
        }
        
        server.GET["/"] = { r in
            return .MovedPermanently("/login")
        }
        
        do {
            try server.start()
        } catch {
            print("Server start error: \(error)")
        }

thanks you very much

**Comment by glock45** [comment]
hi @swierpa :) please have a look at the sample code below:
```
class ViewController: UIViewController {
    
    private var server: HttpServer?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let server = HttpServer();
        
        server.get["/upload"] = { r in
            return .OK(.Html("<form method=\"POST\" action=\"/upload\" enctype=\"multipart/form-data\">" +
                "<input name=\"my_file\" type=\"file\"/>" +
                "<button type=\"submit\">Send File</button>" +
            "</form>"))
        }
        server.post["/upload"] = { r in
            if let myFileMultipart = r.parseMultiPartFormData().filter({ $0.name == "my_file" }).first {
                guard let documentsUrl = NSFileManager.defaultManager().URLsForDirectory(.DocumentDirectory, inDomains: .UserDomainMask).first else {
                    return .InternalServerError
                }
                let data: NSData = myFileMultipart.body.withUnsafeBufferPointer { pointer in
                    return NSData(bytes: pointer.baseAddress, length: myFileMultipart.body.count)
                }
                guard let fileSaveUrl = NSURL(string: "name_for_file.txt", relativeToURL: documentsUrl) else {
                    return .InternalServerError
                }
                print(fileSaveUrl)
                data.writeToURL(fileSaveUrl, atomically: true)
                return .OK(.Html("Your file has been uploaded !"))
            }
            return .InternalServerError
        }
        
        do {
            try server.start(9099)
        } catch {
            print("Server start error: \(error)")
        }
        self.server = server
    }
}
```
best,
dk

**Comment by theRealGupta** [comment]
Hi @glock45 
Thank you for the solution its help a lot to me. but your solution is outdated because of the swift update.
so I did some Changes in your solution. **_Please verify that._** 

```
server.post["/upload"] = { r in
        if let multipart = r.parseMultiPartFormData().filter({ $0.name == "newfile" }).first {
            guard let documentsUrl = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
                return .internalServerError
            }
            let data: NSData = multipart.body.withUnsafeBufferPointer { pointer in
                return NSData(bytes: pointer.baseAddress, length: multipart.body.count)
            }
            
            guard let fileSaveUrl = NSURL(string: multipart.fileName ?? "NoNameFile.txt", relativeTo: documentsUrl) else {
                return .internalServerError
            }
            print(fileSaveUrl)
            data.write(to: fileSaveUrl as URL, atomically: true)
            return HttpResponse.ok(.html("Your file has been uploaded !"))
        }
        return .internalServerError
    }

```
 Thank you,
Anup Gupta

**Comment by theRealGupta** [comment]
**How to Upload Folder ???**  

I am able to upload a single file successfully. 
selection of the folder and and in **`server.post["/upload"]`**  I am geeting all files of folder. 
but unable to upload folder.
