### ISSUE TITLE
Post

### ISSUE THREAD

**Issue by matthewdias** [glock45/swifter#97]
The README is kind of vague, so I was wondering if it would be possible to receive data over http, and then do something with that data in the app. If this is possible, how would I do it with swifter?

**Comment by SwimByteRun** [comment]
There is an example of handling POST methods in /Sources/DemoServer.swift
```swift
server.POST["/upload"] = { r in
        var response = ""
        for multipart in r.parseMultiPartFormData() {
            response += "Name: \(multipart.name) File name: \(multipart.fileName) Size: \(multipart.body.count)<br>"
        }
        return HttpResponse.OK(.Html(response))
    }
```

You'll need to use `parseMultiPartFormData` on the request object to handle the `multipart/form-data` HTTP content-type

**Comment by glock45** [comment]
@SwimByteRun thanks ! :+1:
