### ISSUE TITLE
Trailing slash on last parameter value

### ISSUE THREAD

**Issue by acerosalazar** [glock45/swifter#98]
Commit 25e9da7 in version 1.1.0, introduces a change in the routine that parses the URL parameters that causes the [last parameter value to have a trailing slash](https://github.com/glock45/swifter/blob/master/Sources/HttpRouter.swift#L87)

**Comment by glock45** [comment]
@acerosalazar nice shot :) thank you for the report. I've fixed it here ( https://github.com/glock45/swifter/commit/1ce84ca3fff1f3bf0b27978af15408c2e6d9f024 ).

I started to build tests suite for Swifter. HttpRoute is the next class I am going to cover by the tests.
